apiVersion: kairon.zyvor.dev/v1alpha1
kind: Machine
metadata:
  name: ubuntu-dev
  namespace: default
spec:
  image:
    path: /var/lib/fluxvm/images/ubuntu-24.04.qcow2
  resources:
    cpu: "2"
    memory: 2Gi
  runtime:
    backend: qemu
  network:
    mode: tap
    netns: true
  cloudInit:
    userData: |
      #cloud-config
      users:
        - name: ubuntu
          sudo: ALL=(ALL) NOPASSWD:ALL
          shell: /bin/bash
  placement:
    architecture: amd64
  powerState: Running
