# Copyright 2026 Zyvor · https://zyvor.dev
# SPDX-License-Identifier: Apache-2.0

apiVersion: kairon.zyvor.dev/v1alpha1
kind: MachineInstanceType
metadata:
  name: standard-2x4
  namespace: default
spec:
  resources:
    cpu: "2"
    memory: 4Gi
---
apiVersion: kairon.zyvor.dev/v1alpha1
kind: Machine
metadata:
  name: web-1
  namespace: default
spec:
  instanceTypeName: standard-2x4
  image:
    path: /var/lib/fluxvm/images/ubuntu-24.04.qcow2
  runtime:
    backend: qemu
  powerState: Running
