# Copyright 2026 Zyvor · https://zyvor.dev
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: machinesnapshots.kairon.zyvor.dev
spec:
  group: kairon.zyvor.dev
  scope: Namespaced
  names:
    plural: machinesnapshots
    singular: machinesnapshot
    kind: MachineSnapshot
    shortNames:
    - kms
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Machine
      type: string
      jsonPath: .spec.machineName
    - name: Phase
      type: string
      jsonPath: .status.phase
    - name: Ready
      type: boolean
      jsonPath: .status.readyToUse
    schema:
      openAPIV3Schema:
        type: object
        required:
        - spec
        properties:
          spec:
            type: object
            required:
            - machineName
            properties:
              machineName:
                type: string
                minLength: 1
              volumeSnapshotClassName:
                type: string
          status:
            type: object
            properties:
              phase:
                type: string
              message:
                type: string
              readyToUse:
                type: boolean
              volumeSnapshots:
                type: array
                items:
                  type: object
                  required:
                  - volumeName
                  - volumeSnapshotName
                  properties:
                    volumeName:
                      type: string
                    volumeSnapshotName:
                      type: string
                    readyToUse:
                      type: boolean
