# Copyright 2026 Zyvor · https://zyvor.dev
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: machinepools.kairon.zyvor.dev
spec:
  group: kairon.zyvor.dev
  scope: Namespaced
  names:
    plural: machinepools
    singular: machinepool
    kind: MachinePool
    shortNames:
    - mpool
  versions:
  - name: v1beta1
    served: true
    storage: true
    subresources: &subresources
      status: {}
      scale:
        specReplicasPath: .spec.replicas
        statusReplicasPath: .status.replicas
        labelSelectorPath: .status.selector
    additionalPrinterColumns: &columns
    - name: Warm
      type: integer
      jsonPath: .spec.replicas
    - name: Ready
      type: integer
      jsonPath: .status.readyReplicas
    - name: Claimed
      type: integer
      jsonPath: .status.claimed
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
    schema: &schema
      openAPIV3Schema:
        type: object
        required:
        - spec
        properties:
          spec:
            type: object
            required:
            - replicas
            - template
            properties:
              replicas:
                type: integer
                minimum: 0
              template:
                type: object
                required:
                - spec
                properties:
                  labels:
                    type: object
                    additionalProperties:
                      type: string
                  # Same shape as a Machine's spec; see machinesets.yaml.
                  spec:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            properties:
              replicas:
                type: integer
              readyReplicas:
                type: integer
              claimed:
                type: integer
              selector:
                type: string
              message:
                type: string
  - name: v1alpha1
    served: true
    storage: false
    subresources: *subresources
    additionalPrinterColumns: *columns
    schema: *schema
