# Copyright 2026 Zyvor · https://zyvor.dev
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: networksecuritygroups.kairon.zyvor.dev
spec:
  group: kairon.zyvor.dev
  scope: Namespaced
  names:
    plural: networksecuritygroups
    singular: networksecuritygroup
    kind: NetworkSecurityGroup
    shortNames:
    - knsg
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Group
      type: string
      jsonPath: .spec.groupName
    - name: Phase
      type: string
      jsonPath: .status.phase
    - name: Identity
      type: integer
      jsonPath: .status.identity
    schema:
      openAPIV3Schema:
        type: object
        required:
        - spec
        properties:
          spec:
            type: object
            properties:
              groupName:
                type: string
              labels:
                type: array
                items:
                  type: string
              priority:
                type: integer
                minimum: 0
              description:
                type: string
              policy:
                type: object
                properties:
                  defaultAllow:
                    type: boolean
                  allowCidrs:
                    type: array
                    items:
                      type: string
                  denyCidrs:
                    type: array
                    items:
                      type: string
                  allowPorts:
                    type: array
                    items:
                      type: string
                  maxEgressMbps:
                    type: integer
                    minimum: 0
                  maxEgressPps:
                    type: integer
                    minimum: 0
                  allowFqdns:
                    type: array
                    items:
                      type: string
                  groups:
                    type: array
                    items:
                      type: string
                  labels:
                    type: array
                    items:
                      type: string
                  entities:
                    type: array
                    items:
                      type: string
                  auditMode:
                    type: boolean
                  allowIcmp:
                    type: boolean
                  sampleRate:
                    type: integer
                    minimum: 0
          status:
            type: object
            properties:
              phase:
                type: string
              message:
                type: string
              identity:
                type: integer
              appliedOn:
                type: string
