#!/usr/bin/env python3
# Copyright 2026 Zyvor · https://zyvor.dev
# SPDX-License-Identifier: Apache-2.0

"""Write deploy/rbac.yaml from the Helm chart's RBAC objects.

The chart (charts/kairon/templates) is the single source of truth for
ServiceAccounts, (Cluster)Roles and bindings. Hosts that run Kairon as
systemd units apply this bundle with `kubectl apply --server-side`
(deploy-remote.sh --apply-rbac) instead of installing the chart. Run
`make rbac-bundle` after editing templates; `make helm-check` fails on drift.
"""

import re
import subprocess
import sys
from pathlib import Path

root = Path(__file__).resolve().parents[1]
KINDS = {"ServiceAccount", "ClusterRole", "ClusterRoleBinding", "Role", "RoleBinding"}
HEADER = (
    "# Copyright 2026 Zyvor · https://zyvor.dev\n"
    "# SPDX-License-Identifier: Apache-2.0\n"
    "# Generated by scripts/gen-rbac-bundle.py from charts/kairon. Do not edit.\n"
)
# Every optional RBAC branch on, so the bundle is the superset an operator can
# trim; webhook values are the CI stubs fleet.enabled insists on.
SETS = [
    "ui.enabled=true",
    "fleet.enabled=true",
    "webhook.enabled=true",
    "webhook.tlsSecretName=ci-webhook-tls",
    "webhook.caBundle=Y2ktY2EtYnVuZGxl",
    "migration.dataplaneTlsSecretName=ci-migration-dataplane",
]


def render() -> str:
    cmd = ["helm", "template", "kairon", str(root / "charts/kairon"), "--namespace", "kairon-system"]
    for s in SETS:
        cmd += ["--set", s]
    return subprocess.run(cmd, check=True, capture_output=True, text=True).stdout


def kind_of(doc: str) -> str:
    m = re.search(r"^kind:\s*(\S+)", doc, re.M)
    return m.group(1) if m else ""


def clean(doc: str) -> str:
    doc = re.sub(r"^# Source:.*\n", "", doc, flags=re.M)
    doc = re.sub(r"^\s*(helm\.sh/chart|app\.kubernetes\.io/managed-by):.*\n", "", doc, flags=re.M)
    return doc.strip("\n") + "\n"


def bundle() -> str:
    docs = [clean(d) for d in re.split(r"^---\s*$", render(), flags=re.M)]
    keep = [d for d in docs if kind_of(d) in KINDS]
    keep.sort(key=lambda d: (list(("ServiceAccount", "ClusterRole", "Role", "ClusterRoleBinding", "RoleBinding")).index(kind_of(d)), d))
    return HEADER + "---\n" + "---\n".join(keep)


if __name__ == "__main__":
    out = root / "deploy/rbac.yaml"
    text = bundle()
    if "--check" in sys.argv:
        if out.read_text() != text:
            print("deploy/rbac.yaml is stale: run `make rbac-bundle`", file=sys.stderr)
            sys.exit(1)
    else:
        out.write_text(text)
