#!/usr/bin/env python3
# Copyright 2026 Zyvor · https://zyvor.dev
# SPDX-License-Identifier: Apache-2.0

"""Write deploy/crd.yaml from charts/kairon/crds/*.yaml.

The chart CRDs are the source of truth. Run `make crds` after editing them;
scripts/validate.py fails when the bundle drifts.
"""

from pathlib import Path

root = Path(__file__).resolve().parents[1]
HEADER = (
    "# Copyright 2026 Zyvor · https://zyvor.dev\n"
    "# SPDX-License-Identifier: Apache-2.0\n"
    "# Generated by scripts/gen-crd-bundle.py from charts/kairon/crds. Do not edit.\n"
)


def body(path: Path) -> str:
    lines = path.read_text().splitlines()
    while lines and (lines[0].startswith("#") or not lines[0].strip() or lines[0] == "---"):
        lines.pop(0)
    return "\n".join(lines).rstrip() + "\n"


def bundle() -> str:
    parts = [body(p) for p in sorted((root / "charts/kairon/crds").glob("*.yaml"))]
    return HEADER + "---\n" + "---\n".join(parts)


if __name__ == "__main__":
    (root / "deploy/crd.yaml").write_text(bundle())
